### ISSUE TITLE
Lazy Load Subdisplays

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/typhos#119] opened 2018-10-24 16:59 UTC
Certain subdisplays we want to have up and running even when they are hidden (plotting, logging). We however most displays we want to load only when the user requests them. This should be an option when you add a tool

**Comment by klauer** [comment] 2020-05-11 23:29
#287 was a duplicate of this and I didn't realize. Closing.

**Closed by klauer** 2020-05-11 23:29 UTC
Labels: Backend
